name: my workflow

on:
  push:
    branches:
      - '1.1v'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: my workflow
        run: cd RELEASE && server.py
